services:
  gemini_multimodal_chatbot:
    container_name: gemini_multimodal_chatbot
    command: streamlit run gemini_multimodal_chatbot.py --server.port=8501 --server.address=0.0.0.0
    restart: always
    ports:
      - 127.0.0.1:8501:8501
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/app
