services:
  gemini_multimodal_chatbot:
    container_name: gemini_multimodal_chatbot
    command: /app/start.sh
    restart: always

    ports:
      - "8501:8501"
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/app
